# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMG = "debian/stretch64"
BOX_VER = "9.6.0"
BOX_COUNT = 3
BOX_NAME = "nettest"
BOX_CPU = 1
BOX_MEM = 512
BOX_IP = "192.168.121.20"

Vagrant.configure("2") do |config|
    (1..BOX_COUNT).each do |i|
        config.vm.define BOX_NAME+"#{i}" do |subconfig|
            subconfig.vm.box = BOX_IMG
            subconfig.vm.hostname = BOX_NAME+"#{i}"
            subconfig.vm.provider "virtualbox" do |v|
                v.name = BOX_NAME+"#{i}"
                v.memory = BOX_MEM
                v.cpus = BOX_CPU
            end

            subconfig.vm.synced_folder ".", "/vagrant", disabled: true

            subconfig.vm.network "public_network", ip: BOX_IP+"#{i}"
            subconfig.vm.network "public_network", ip: "10.0.121.#{i}"

            subconfig.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/me.pub"
            subconfig.vm.provision "shell", path: "provisioning.sh"
        end
    end
end