# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMG = "debian/stretch64"
#BOX_VER = "9.5.0"
BOX_COUNT = 1
BOX_NAME = "deb"
BOX_CPU = 1
BOX_MEM = 1024
BOX_IP = "192.168.12.4"

Vagrant.configure("2") do |config|
    (1..BOX_COUNT).each do |i|
        config.vm.define BOX_NAME+"#{i}" do |subconfig|
            subconfig.vm.box = BOX_IMG
            #subconfig.vm.box_version = BOX_VER
            subconfig.vm.hostname = BOX_NAME+"#{i}"

            subconfig.vm.provider "virtualbox" do |v|
                v.name = BOX_NAME+"#{i}"
                v.memory = BOX_MEM
                v.cpus = BOX_CPU

                #file_to_disk = "disk2#{i}.vdi"
                #unless File.exist?(file_to_disk)
                #    v.customize ['createhd', '--filename', file_to_disk, '--size', 1 * 1024]
                #end
                #v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
            end

            subconfig.vm.synced_folder ".", "/vagrant", disabled: true

            #subconfig.vm.network "private_network", ip: BOX_IP+"#{i}", virtualbox__intnet: true
            subconfig.vm.network "public_network"
            #subconfig.ssh.host = "192.168.1.57"
            #subconfig.vm.network "forwarded_port", guest: 22, host: "220#{i}", id: "ssh", host_ip: "192.168.1.57"
            #subconfig.vm.network "forwarded_port", guest: 12121, host: "1200#{i}"

            #subconfig.vm.provision "shell", inline: "sed -i 's/# alias ll/alias ll/g' /root/.bashrc"
            subconfig.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/me.pub"
            subconfig.vm.provision "shell", path: "provisioning.sh"
        end
    end
end